repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, perf, deps, chore, refactor, test, build, ci, docs, style, revert]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/yaml-schema/yaml-schema
    rev: 30646e2e97edc82a54b085a4e567a99487bd8abb
    hooks:
      - id: ys
        name: Validate Project Data
        files: ^pg_atlas/data/projects/.*\.yml$
