"""add github dependents observation storage

Revision ID: 5d5833f64218
Revises: 66ac36af6383
Create Date: 2026-08-25 12:14:08.190758+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5d5833f64218"
down_revision: Union[str, Sequence[str], None] = "66ac36af6383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_dependents_crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_repo_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "complete", "partial", "failed", "superseded", name="github_dependents_run_status"),
            nullable=False,
        ),
        sa.Column("listing_complete", sa.Boolean(), nullable=False),
        sa.Column("counts_complete", sa.Boolean(), nullable=False),
        sa.Column("listing_incomplete_reason", sa.String(length=64), nullable=True),
        sa.Column("counts_incomplete_reason", sa.String(length=64), nullable=True),
        sa.Column("repos_total_reported", sa.Integer(), nullable=True),
        sa.Column("packages_total_reported", sa.Integer(), nullable=True),
        sa.Column("public_repos_observed", sa.Integer(), nullable=False),
        sa.Column("packages_scanned", sa.Integer(), nullable=True),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=True),
        sa.Column("app_version", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.String(length=4096), nullable=True),
        sa.Column("snapshot_fingerprint", sa.LargeBinary(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_repo_id"], ["repos.id"], name=op.f("fk_github_dependents_crawl_runs_source_repo_id_repos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_dependents_crawl_runs")),
    )
    op.create_index(
        "ix_github_dependents_crawl_runs_source_id",
        "github_dependents_crawl_runs",
        ["source_repo_id", "id"],
        unique=False,
    )
    op.create_table(
        "github_dependent_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_repo_id", sa.Integer(), nullable=False),
        sa.Column("dependent_key", sa.String(length=512), nullable=False),
        sa.Column("dependent_canonical_id", sa.String(length=512), nullable=False),
        sa.Column("observed_owner", sa.String(length=256), nullable=False),
        sa.Column("observed_repo_name", sa.String(length=256), nullable=False),
        sa.Column("dependent_repo_url", sa.String(length=1024), nullable=False),
        sa.Column("resolved_repo_id", sa.Integer(), nullable=True),
        sa.Column("package_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_seen_run_id", sa.Integer(), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_by_run_id", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_seen_run_id"],
            ["github_dependents_crawl_runs.id"],
            name=op.f("fk_github_dependent_observations_last_seen_run_id_github_dependents_crawl_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_repo_id"],
            ["repos.id"],
            name=op.f("fk_github_dependent_observations_resolved_repo_id_repos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["retired_by_run_id"],
            ["github_dependents_crawl_runs.id"],
            name=op.f("fk_github_dependent_observations_retired_by_run_id_github_dependents_crawl_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_repo_id"], ["repos.id"], name=op.f("fk_github_dependent_observations_source_repo_id_repos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_dependent_observations")),
        sa.UniqueConstraint("source_repo_id", "dependent_key", name=op.f("uq_github_dependent_observations_source_repo_id")),
    )
    op.create_index(
        "ix_github_dependent_observations_source_active",
        "github_dependent_observations",
        ["source_repo_id", "dependent_key"],
        unique=False,
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_github_dependent_observations_source_active",
        table_name="github_dependent_observations",
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    op.drop_table("github_dependent_observations")
    op.drop_index("ix_github_dependents_crawl_runs_source_id", table_name="github_dependents_crawl_runs")
    op.drop_table("github_dependents_crawl_runs")
    sa.Enum(name="github_dependents_run_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
