"""create initial schema

Revision ID: f3d946ade07e
Revises:
Create Date: 2026-03-03 23:47:03.633584+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f3d946ade07e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contributors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contributors")),
    )
    op.create_index("ix_contributors_email_hash", "contributors", ["email_hash"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_id", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("project_type", sa.Enum("public-good", "scf-project", name="project_type"), nullable=False),
        sa.Column(
            "activity_status",
            sa.Enum("live", "in-dev", "discontinued", "non-responsive", name="activity_status"),
            nullable=False,
        ),
        sa.Column("git_org_url", sa.String(length=512), nullable=True),
        sa.Column("pony_factor", sa.Integer(), nullable=True),
        sa.Column("criticality_score", sa.Integer(), nullable=True),
        sa.Column("adoption_score", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_canonical_id"), "projects", ["canonical_id"], unique=True)
    op.create_table(
        "repo_vertices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_id", sa.String(length=512), nullable=False),
        sa.Column("vertex_type", sa.Enum("repo", "external-repo", name="vertex_type"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repo_vertices")),
    )
    op.create_index(op.f("ix_repo_vertices_canonical_id"), "repo_vertices", ["canonical_id"], unique=True)
    op.create_table(
        "sbom_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_claim", sa.String(length=256), nullable=False),
        sa.Column("actor_claim", sa.String(length=128), nullable=False),
        sa.Column("sbom_content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("artifact_path", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.Enum("pending", "processed", "failed", name="submission_status"), nullable=False),
        sa.Column("error_detail", sa.String(length=4096), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sbom_submissions")),
    )
    op.create_index("ix_sbom_submissions_content_hash", "sbom_submissions", ["sbom_content_hash"], unique=False)
    op.create_index("ix_sbom_submissions_repository_claim", "sbom_submissions", ["repository_claim"], unique=False)
    op.create_table(
        "depends_on",
        sa.Column("in_vertex_id", sa.Integer(), nullable=False),
        sa.Column("out_vertex_id", sa.Integer(), nullable=False),
        sa.Column("version_range", sa.String(length=256), nullable=True),
        sa.Column("confidence", sa.Enum("verified-sbom", "inferred-shadow", name="edge_confidence"), nullable=False),
        sa.ForeignKeyConstraint(["in_vertex_id"], ["repo_vertices.id"], name=op.f("fk_depends_on_in_vertex_id_repo_vertices")),
        sa.ForeignKeyConstraint(
            ["out_vertex_id"], ["repo_vertices.id"], name=op.f("fk_depends_on_out_vertex_id_repo_vertices")
        ),
        sa.PrimaryKeyConstraint("in_vertex_id", "out_vertex_id", name=op.f("pk_depends_on")),
    )
    op.create_table(
        "external_repos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("latest_version", sa.String(length=256), nullable=False),
        sa.Column("repo_url", sa.String(length=512), nullable=True),
        sa.Column("criticality_score", sa.Integer(), nullable=True),
        sa.Column("releases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["repo_vertices.id"], name=op.f("fk_external_repos_id_repo_vertices")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_repos")),
    )
    op.create_table(
        "repos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("visibility", sa.Enum("public", "private", name="visibility"), nullable=False),
        sa.Column("latest_version", sa.String(length=256), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("latest_commit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("repo_url", sa.String(length=512), nullable=True),
        sa.Column("pony_factor", sa.Integer(), nullable=True),
        sa.Column("criticality_score", sa.Integer(), nullable=True),
        sa.Column("adoption_downloads", sa.Integer(), nullable=True),
        sa.Column("adoption_stars", sa.Integer(), nullable=True),
        sa.Column("adoption_forks", sa.Integer(), nullable=True),
        sa.Column("releases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["repo_vertices.id"], name=op.f("fk_repos_id_repo_vertices")),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_repos_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repos")),
    )
    op.create_table(
        "contributed_to",
        sa.Column("contributor_id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("number_of_commits", sa.Integer(), nullable=False),
        sa.Column("first_commit_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_commit_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["contributors.id"],
            name=op.f("fk_contributed_to_contributor_id_contributors"),
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repos.id"], name=op.f("fk_contributed_to_repo_id_repos")),
        sa.PrimaryKeyConstraint("contributor_id", "repo_id", name=op.f("pk_contributed_to")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contributed_to")
    op.drop_table("repos")
    op.drop_table("external_repos")
    op.drop_table("depends_on")
    op.drop_index("ix_sbom_submissions_repository_claim", table_name="sbom_submissions")
    op.drop_index("ix_sbom_submissions_content_hash", table_name="sbom_submissions")
    op.drop_table("sbom_submissions")
    op.drop_index(op.f("ix_repo_vertices_canonical_id"), table_name="repo_vertices")
    op.drop_table("repo_vertices")
    op.drop_index(op.f("ix_projects_canonical_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_contributors_email_hash", table_name="contributors")
    op.drop_table("contributors")
    # Drop PostgreSQL enum types that were created implicitly with the tables above.
    op.execute("DROP TYPE IF EXISTS edge_confidence")
    op.execute("DROP TYPE IF EXISTS visibility")
    op.execute("DROP TYPE IF EXISTS submission_status")
    op.execute("DROP TYPE IF EXISTS vertex_type")
    op.execute("DROP TYPE IF EXISTS activity_status")
    op.execute("DROP TYPE IF EXISTS project_type")
    # ### end Alembic commands ###
